Add rebuild Actions using release file

diff --git a/.github/workflows/use-releases-file-to-build.yml b/.github/workflows/use-releases-file-to-build.yml
--- a/.github/workflows/use-releases-file-to-build.yml
+++ b/.github/workflows/use-releases-file-to-build.yml
@@ -3,7 +3,7 @@
 # Copyright (C) 2021 https://github.com/ophub/rockchip-armbian
 #==========================================================================
 
-name: Build armbian
+name: Use Releases file to build armbian
 
 on:
   repository_dispatch:
@@ -76,42 +76,32 @@ jobs:
           sudo -E apt-get -qq autoremove --purge
           sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "${TZ}"
-          echo "ARMBIAN_RELEASE=${{ github.event.inputs.set_release }}" >> ${GITHUB_ENV}
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Download source code
+      - name: Download Armbian from Releases
         id: down
         if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
-          git clone --depth 1 https://github.com/armbian/build.git
+          armbian_buildpath="build/output/images"
+          [[ -d "${armbian_buildpath}" ]] || mkdir -p "${armbian_buildpath}"
+          down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
+          down_path="Armbian_rockchip_${{ github.event.inputs.set_release }}.*/tmp.img.gz"
+
+          # down_filename: Armbian_rockchip_jammy_05.17.1924/tmp.img.gz
+          down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
+          down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
+          [[ -z "${down_file}" ]] && echo "Invalid download file." && exit 1
+          wget -q -P "${armbian_buildpath}" "${down_file}" && sync
+          cd "${armbian_buildpath}" && gzip -df *.img.gz && sync
+
+          echo "ARMBIAN_RELEASE=${{ github.event.inputs.set_release }}" >> ${GITHUB_ENV}
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Compile Armbian [ ${{ env.ARMBIAN_RELEASE }} ]
-        id: compile
-        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
-        run: |
-          # Compile method and parameter description: https://docs.armbian.com/Developer-Guide_Build-Options
-          cd build/
-          sudo ./compile.sh RELEASE=${{ env.ARMBIAN_RELEASE }} BOARD=rock-5b BRANCH=legacy BUILD_DESKTOP=no HOST=armbian EXPERT=yes \
-                            BUILD_MINIMAL=no KERNEL_ONLY=no KERNEL_CONFIGURE=no CLEAN_LEVEL=make,debs COMPRESS_OUTPUTIMAGE="sha,gz"
-          (cd build/output/images && mv Armbian_*.img.gz tmp.img.gz)
-          echo "build_tag=Armbian_rockchip_${{ env.ARMBIAN_RELEASE }}_$(date +"%m.%d.%H%M")" >> ${GITHUB_OUTPUT}
-          echo "status=success" >> ${GITHUB_OUTPUT}
-
-      - name: Upload Armbian image to Release
-        uses: ncipollo/release-action@main
-        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
-        with:
-          tag: ${{ steps.compile.outputs.build_tag }}
-          artifacts: build/output/images/*.img.gz
-          allowUpdates: true
-          token: ${{ secrets.GH_TOKEN }}
-
-      - name: Rebuild Armbian for rockchip
+      - name: Rebuild Armbian [ ${{ env.ARMBIAN_RELEASE }} ]
         uses: ophub/rockchip-armbian@main
-        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
+        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
         with:
-          armbian_path: build/output/images/*.img.gz
+          armbian_path: build/output/images/*.img
           armbian_soc: ${{ github.event.inputs.armbian_soc }}
           armbian_kernel: ${{ github.event.inputs.armbian_kernel }}
           auto_kernel: ${{ github.event.inputs.auto_kernel }}
@@ -119,11 +109,11 @@ jobs:
           armbian_fstype: ${{ github.event.inputs.armbian_fstype }}
           armbian_sign: ${{ github.event.inputs.armbian_sign }}
 
-      - name: Upload Rebuild image to Release
+      - name: Upload Armbian image to Release
         uses: ncipollo/release-action@main
         if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
         with:
-          tag: ${{ steps.compile.outputs.build_tag }}
+          tag: Armbian_rockchip_${{ env.ARMBIAN_RELEASE }}_${{ env.PACKAGED_OUTPUTDATE }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GH_TOKEN }}
@@ -133,4 +123,3 @@ jobs:
             Default username: root
             Default password: 1234
             Update command: armbian-update
-
